var a;a||(a=typeof Module !== 'undefined' ? Module : {});var k={},m;for(m in a)a.hasOwnProperty(m)&&(k[m]=a[m]);a.arguments=[];a.thisProgram="./this.program";a.quit=function(b,c){throw c;};a.preRun=[];a.postRun=[];var n=!1,p=!1,q=!1,t=!1;
if(a.ENVIRONMENT)if("WEB"===a.ENVIRONMENT)n=!0;else if("WORKER"===a.ENVIRONMENT)p=!0;else if("NODE"===a.ENVIRONMENT)q=!0;else if("SHELL"===a.ENVIRONMENT)t=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else n="object"===typeof window,p="function"===typeof importScripts,q="object"===typeof process&&"function"===typeof require&&!n&&!p,t=!n&&!q&&!p;
if(q){var u,v;a.read=function(b,c){u||(u=require("fs"));v||(v=require("path"));b=v.normalize(b);b=u.readFileSync(b);return c?b:b.toString()};a.readBinary=function(b){b=a.read(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);return b};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(b){if(!(b instanceof w))throw b;});process.on("unhandledRejection",
function(){process.exit(1)});a.inspect=function(){return"[Emscripten Module object]"}}else if(t)"undefined"!=typeof read&&(a.read=function(b){return read(b)}),a.readBinary=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");assert("object"===typeof b);return b},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=arguments),"function"===typeof quit&&(a.quit=function(b){quit(b)});else if(n||p)a.read=function(b){var c=
new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},p&&(a.readBinary=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),a.readAsync=function(b,c,e){var d=new XMLHttpRequest;d.open("GET",b,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?c(d.response):e()};d.onerror=e;d.send(null)},a.setWindowTitle=function(b){document.title=b};
a.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;a.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||a.print;a.print=a.print;a.printErr=a.printErr;for(m in k)k.hasOwnProperty(m)&&(a[m]=k[m]);k=void 0;function x(b){var c;c||(c=16);return Math.ceil(b/c)*c}var y=0;function assert(b,c){b||z("Assertion failed: "+c)}
function A(b){var c;if(0===c||!b)return"";for(var e=0,d,g=0;;){d=B[b+g>>0];e|=d;if(0==d&&!c)break;g++;if(c&&g==c)break}c||(c=g);d="";if(128>e){for(;0<c;)e=String.fromCharCode.apply(String,B.subarray(b,b+Math.min(c,1024))),d=d?d+e:e,b+=1024,c-=1024;return d}return C(B,b)}var aa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(b,c){for(var e=c;b[e];)++e;if(16<e-c&&b.subarray&&aa)return aa.decode(b.subarray(c,e));for(e="";;){var d=b[c++];if(!d)return e;if(d&128){var g=b[c++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|g);else{var h=b[c++]&63;if(224==(d&240))d=(d&15)<<12|g<<6|h;else{var f=b[c++]&63;if(240==(d&248))d=(d&7)<<18|g<<12|h<<6|f;else{var l=b[c++]&63;if(248==(d&252))d=(d&3)<<24|g<<18|h<<12|f<<6|l;else{var r=b[c++]&63;d=(d&1)<<30|g<<24|h<<18|f<<12|l<<6|r}}}65536>d?e+=String.fromCharCode(d):(d-=
65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d)}}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function ba(b){for(var c=0,e=0;e<b.length;++e){var d=b.charCodeAt(e);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|b.charCodeAt(++e)&1023);127>=d?++c:c=2047>=d?c+2:65535>=d?c+3:2097151>=d?c+4:67108863>=d?c+5:c+6}var g=c+1;c=ca(g);e=c;d=da;if(0<g){g=e+g-1;for(var h=0;h<b.length;++h){var f=b.charCodeAt(h);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|b.charCodeAt(++h)&1023);if(127>=f){if(e>=g)break;d[e++]=f}else{if(2047>=f){if(e+1>=g)break;d[e++]=192|f>>6}else{if(65535>=f){if(e+2>=g)break;d[e++]=224|f>>
12}else{if(2097151>=f){if(e+3>=g)break;d[e++]=240|f>>18}else{if(67108863>=f){if(e+4>=g)break;d[e++]=248|f>>24}else{if(e+5>=g)break;d[e++]=252|f>>30;d[e++]=128|f>>24&63}d[e++]=128|f>>18&63}d[e++]=128|f>>12&63}d[e++]=128|f>>6&63}d[e++]=128|f&63}}d[e]=0}return c}var buffer,da,B,ea,D;
function fa(){a.HEAP8=da=new Int8Array(buffer);a.HEAP16=ea=new Int16Array(buffer);a.HEAP32=D=new Int32Array(buffer);a.HEAPU8=B=new Uint8Array(buffer);a.HEAPU16=new Uint16Array(buffer);a.HEAPU32=new Uint32Array(buffer);a.HEAPF32=new Float32Array(buffer);a.HEAPF64=new Float64Array(buffer)}var E,F,G,H,I,J,K,L;E=F=H=I=J=K=L=0;G=!1;
function ha(){z("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+M+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var N=a.TOTAL_STACK||5242880,M=a.TOTAL_MEMORY||268435456;M<N&&a.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+M+"! (TOTAL_STACK="+N+")");
a.buffer?buffer=a.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(a.wasmMemory=new WebAssembly.Memory({initial:M/65536,maximum:M/65536}),buffer=a.wasmMemory.buffer):buffer=new ArrayBuffer(M),a.buffer=buffer);fa();D[0]=1668509029;ea[1]=25459;if(115!==B[2]||99!==B[3])throw"Runtime error: expected the system to be little-endian!";
function O(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c();else{var e=c.m;"number"===typeof e?void 0===c.a?a.dynCall_v(e):a.dynCall_vi(e,c.a):e(void 0===c.a?null:c.a)}}}var ia=[],P=[],ja=[],ka=[],la=[],Q=!1;function ma(){var b=a.preRun.shift();ia.unshift(b)}var R=0,S=null,T=null;a.preloadedImages={};a.preloadedAudios={};function U(b){return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}
(function(){function b(){try{if(a.wasmBinary)return new Uint8Array(a.wasmBinary);if(a.readBinary)return a.readBinary(g);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(ra){z(ra)}}function c(){return a.wasmBinary||!n&&!p||"function"!==typeof fetch?new Promise(function(c){c(b())}):fetch(g,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+
g+"'";return b.arrayBuffer()}).catch(function(){return b()})}function e(b){function d(b){l=b.exports;if(l.memory){b=l.memory;var c=a.buffer;b.byteLength<c.byteLength&&a.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(b)).set(c);a.buffer=buffer=b;fa()}a.asm=l;a.usingWasm=!0;R--;a.monitorRunDependencies&&a.monitorRunDependencies(R);0==R&&(null!==S&&(clearInterval(S),S=null),T&&(b=T,T=null,b()))}
function e(b){d(b.instance)}function h(b){c().then(function(b){return WebAssembly.instantiate(b,f)}).then(b).catch(function(b){a.printErr("failed to asynchronously prepare wasm: "+b);z(b)})}if("object"!==typeof WebAssembly)return a.printErr("no native wasm support detected"),!1;if(!(a.wasmMemory instanceof WebAssembly.Memory))return a.printErr("no native wasm Memory in use"),!1;b.memory=a.wasmMemory;f.global={NaN:NaN,Infinity:Infinity};f["global.Math"]=Math;f.env=b;R++;a.monitorRunDependencies&&a.monitorRunDependencies(R);
if(a.instantiateWasm)try{return a.instantiateWasm(f,d)}catch(sa){return a.printErr("Module.instantiateWasm callback failed with error: "+sa),!1}a.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||U(g)||"function"!==typeof fetch?h(e):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),f).then(e).catch(function(b){a.printErr("wasm streaming compile failed: "+b);a.printErr("falling back to ArrayBuffer instantiation");h(e)});return{}}var d="asm2wasm_box2d.wast",g="asm2wasm_box2d.wasm",
h="asm2wasm_box2d.temp.asm.js";"function"===typeof a.locateFile&&(U(d)||(d=a.locateFile(d)),U(g)||(g=a.locateFile(g)),U(h)||(h=a.locateFile(h)));var f={global:null,env:null,asm2wasm:{"f64-rem":function(b,c){return b%c},"debugger":function(){debugger}},parent:a},l=null;a.asmPreload=a.asm;var r=a.reallocBuffer;a.reallocBuffer=function(b){if("asmjs"===ta)var c=r(b);else a:{var d=a.usingWasm?65536:16777216;0<b%d&&(b+=d-b%d);d=a.buffer.byteLength;if(a.usingWasm)try{c=-1!==a.wasmMemory.grow((b-d)/65536)?
a.buffer=a.wasmMemory.buffer:null;break a}catch(wa){c=null;break a}c=void 0}return c};var ta="";a.asm=function(b,c){if(!c.table){b=a.wasmTableSize;void 0===b&&(b=1024);var d=a.wasmMaxTableSize;c.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:b,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:b,element:"anyfunc"}):Array(b);a.wasmTable=c.table}c.memoryBase||(c.memoryBase=a.STATIC_BASE);c.tableBase||(c.tableBase=0);(c=
e(c))||z("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return c}})();E=1024;F=E+10768;P.push();a.STATIC_BASE=E;a.STATIC_BUMP=10768;F+=16;var V=0;function W(){V+=4;return D[V-4>>2]}var na={};
function X(b,c){V=c;try{var e=W(),d=W(),g=W();b=0;X.c||(X.c=[null,[],[]],X.i=function(b,c){var d=X.c[b];assert(d);0===c||10===c?((1===b?a.print:a.printErr)(C(d,0)),d.length=0):d.push(c)});for(c=0;c<g;c++){for(var h=D[d+8*c>>2],f=D[d+(8*c+4)>>2],l=0;l<f;l++)X.i(e,B[h+l]);b+=f}return b}catch(r){return"undefined"!==typeof FS&&r instanceof FS.b||z(r),-r.f}}function Y(){void 0===Y.start&&(Y.start=Date.now());return 1E3*(Date.now()-Y.start)|0}assert(!G);var oa=F;F=F+4+15&-16;L=oa;H=I=x(F);J=H+N;K=x(J);
D[L>>2]=K;G=!0;a.wasmTableSize=106;a.wasmMaxTableSize=106;a.g={};
a.h={abort:z,enlargeMemory:function(){ha()},getTotalMemory:function(){return M},abortOnCannotGrowMemory:ha,___assert_fail:function(b,c,e,d){z("Assertion failed: "+A(b)+", at: "+[c?A(c):"unknown filename",e,d?A(d):"unknown function"])},___cxa_pure_virtual:function(){y=!0;throw"Pure virtual function called!";},___setErrNo:function(b){a.___errno_location&&(D[a.___errno_location()>>2]=b);return b},___syscall140:function(b,c){V=c;try{var e=na.j();W();var d=W(),g=W(),h=W();FS.o(e,d,h);D[g>>2]=e.position;
e.l&&0===d&&0===h&&(e.l=null);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof FS.b||z(f),-f.f}},___syscall146:X,___syscall54:function(b,c){V=c;return 0},___syscall6:function(b,c){V=c;try{var e=na.j();FS.close(e);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.b||z(d),-d.f}},_clock:Y,_emscripten_memcpy_big:function(b,c,e){B.set(B.subarray(c,c+e),b);return b},_llvm_trap:function(){z("trap!")},DYNAMICTOP_PTR:L,STACKTOP:I};var pa=a.asm(a.g,a.h,buffer);a.asm=pa;
a._main=function(){return a.asm._main.apply(null,arguments)};var ca=a.stackAlloc=function(){return a.asm.stackAlloc.apply(null,arguments)};a.dynCall_v=function(){return a.asm.dynCall_v.apply(null,arguments)};a.dynCall_vi=function(){return a.asm.dynCall_vi.apply(null,arguments)};a.asm=pa;function w(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}w.prototype=Error();w.prototype.constructor=w;
T=function qa(){a.calledRun||Z([].concat(a.arguments));a.calledRun||(T=qa)};a.callMain=function(b){b=b||[];Q||(Q=!0,O(P));var c=b.length+1,e=ca(4*(c+1));D[e>>2]=ba(a.thisProgram);for(var d=1;d<c;d++)D[(e>>2)+d]=ba(b[d-1]);D[(e>>2)+c]=0;try{var g=a._main(c,e,0);ua(g,!0)}catch(h){h instanceof w||("SimulateInfiniteLoop"==h?a.noExitRuntime=!0:((b=h)&&"object"===typeof h&&h.stack&&(b=[h,h.stack]),a.printErr("exception thrown: "+b),a.quit(1,h)))}finally{}};
function Z(b){function c(){if(!a.calledRun&&(a.calledRun=!0,!y)){Q||(Q=!0,O(P));O(ja);if(a.onRuntimeInitialized)a.onRuntimeInitialized();a._main&&va&&a.callMain(b);if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();la.unshift(c)}O(la)}}b=b||a.arguments;if(!(0<R)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ma();O(ia);0<R||a.calledRun||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},
1);c()},1)):c())}}a.run=Z;function ua(b,c){if(!c||!a.noExitRuntime||0!==b){if(!a.noExitRuntime&&(y=!0,I=void 0,O(ka),a.onExit))a.onExit(b);q&&process.exit(b);a.quit(b,new w(b))}}a.exit=ua;function z(b){if(a.onAbort)a.onAbort(b);void 0!==b?(a.print(b),a.printErr(b),b=JSON.stringify(b)):b="";y=!0;throw"abort("+b+"). Build with -s ASSERTIONS=1 for more info.";}a.abort=z;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();var va=!0;
a.noInitialRun&&(va=!1);a.noExitRuntime=!0;Z([].concat(a.arguments));
