var c;c||(c=typeof Module !== 'undefined' ? Module : {});var g={},m;for(m in c)c.hasOwnProperty(m)&&(g[m]=c[m]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var p=!1,q=!1,r=!1,v=!1;
if(c.ENVIRONMENT)if("WEB"===c.ENVIRONMENT)p=!0;else if("WORKER"===c.ENVIRONMENT)q=!0;else if("NODE"===c.ENVIRONMENT)r=!0;else if("SHELL"===c.ENVIRONMENT)v=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else p="object"===typeof window,q="function"===typeof importScripts,r="object"===typeof process&&"function"===typeof require&&!p&&!q,v=!p&&!r&&!q;
if(r){var w,x;c.read=function(a,b){w||(w=require("fs"));x||(x=require("path"));a=x.normalize(a);a=w.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=c);process.on("uncaughtException",function(a){if(!(a instanceof z))throw a;});process.on("unhandledRejection",
function(){process.exit(1)});c.inspect=function(){return"[Emscripten Module object]"}}else if(v)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(p||q)c.read=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,e){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):e()};d.onerror=e;d.send(null)},c.setWindowTitle=function(a){document.title=a};
c.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;c.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||c.print;c.print=c.print;c.printErr=c.printErr;for(m in g)g.hasOwnProperty(m)&&(c[m]=g[m]);g=void 0;function A(a){assert(!aa);var b=B;B=B+a+15&-16;return b}function ba(a){assert(C);var b=D[C>>2];a=b+a+15&-16;D[C>>2]=a;if(a=a>=E)ca(),a=!0;return a?(D[C>>2]=b,0):b}
function da(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ea=0;function assert(a,b){a||F("Assertion failed: "+b)}function fa(a,b){if("number"===typeof a){var e=!0;var d=a}else e=!1,d=a.length;b=4==b?h:["function"===typeof ha?ha:A,ia,A,ba][void 0===b?2:b](Math.max(d,1));if(e){var h=b;assert(0==(b&3));for(a=b+(d&-4);h<a;h+=4)D[h>>2]=0;for(a=b+d;h<a;)G[h++>>0]=0;return b}a.subarray||a.slice?H.set(a,b):H.set(new Uint8Array(a),b);return b}
function ja(a){var b;if(0===b||!a)return"";for(var e=0,d,h=0;;){d=H[a+h>>0];e|=d;if(0==d&&!b)break;h++;if(b&&h==b)break}b||(b=h);d="";if(128>e){for(;0<b;)e=String.fromCharCode.apply(String,H.subarray(a,a+Math.min(b,1024))),d=d?d+e:e,a+=1024,b-=1024;return d}return ka(H,a)}var la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ka(a,b){for(var e=b;a[e];)++e;if(16<e-b&&a.subarray&&la)return la.decode(a.subarray(b,e));for(e="";;){var d=a[b++];if(!d)return e;if(d&128){var h=a[b++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|h);else{var k=a[b++]&63;if(224==(d&240))d=(d&15)<<12|h<<6|k;else{var f=a[b++]&63;if(240==(d&248))d=(d&7)<<18|h<<12|k<<6|f;else{var l=a[b++]&63;if(248==(d&252))d=(d&3)<<24|h<<18|k<<12|f<<6|l;else{var t=a[b++]&63;d=(d&1)<<30|h<<24|k<<18|f<<12|l<<6|t}}}65536>d?e+=String.fromCharCode(d):(d-=
65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d)}}
function ma(a,b,e,d){if(!(0<d))return 0;var h=e;d=e+d-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|a.charCodeAt(++k)&1023);if(127>=f){if(e>=d)break;b[e++]=f}else{if(2047>=f){if(e+1>=d)break;b[e++]=192|f>>6}else{if(65535>=f){if(e+2>=d)break;b[e++]=224|f>>12}else{if(2097151>=f){if(e+3>=d)break;b[e++]=240|f>>18}else{if(67108863>=f){if(e+4>=d)break;b[e++]=248|f>>24}else{if(e+5>=d)break;b[e++]=252|f>>30;b[e++]=128|f>>24&63}b[e++]=128|f>>18&63}b[e++]=128|
f>>12&63}b[e++]=128|f>>6&63}b[e++]=128|f&63}}b[e]=0;return e-h}function na(a){for(var b=0,e=0;e<a.length;++e){var d=a.charCodeAt(e);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++e)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function oa(a){var b=na(a)+1,e=ia(b);ma(a,G,e,b);return e}var buffer,G,H,pa,D;
function qa(){c.HEAP8=G=new Int8Array(buffer);c.HEAP16=pa=new Int16Array(buffer);c.HEAP32=D=new Int32Array(buffer);c.HEAPU8=H=new Uint8Array(buffer);c.HEAPU16=new Uint16Array(buffer);c.HEAPU32=new Uint32Array(buffer);c.HEAPF32=new Float32Array(buffer);c.HEAPF64=new Float64Array(buffer)}var I,B,aa,ra,J,sa,ta,C;I=B=ra=J=sa=ta=C=0;aa=!1;
function ca(){F("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+E+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var ua=c.TOTAL_STACK||5242880,E=c.TOTAL_MEMORY||268435456;E<ua&&c.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+E+"! (TOTAL_STACK="+ua+")");
c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:E/65536,maximum:E/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(E),c.buffer=buffer);qa();D[0]=1668509029;pa[1]=25459;if(115!==H[2]||99!==H[3])throw"Runtime error: expected the system to be little-endian!";
function K(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var e=b.F;"number"===typeof e?void 0===b.h?c.dynCall_v(e):c.dynCall_vi(e,b.h):e(void 0===b.h?null:b.h)}}}var va=[],wa=[],xa=[],ya=[],za=[],L=!1;function Ca(){var a=c.preRun.shift();va.unshift(a)}var M=0,Da=null,N=null;c.preloadedImages={};c.preloadedAudios={};function O(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(h);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(n){F(n)}}function b(){return c.wasmBinary||!p&&!q||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(h,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+h+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function e(a){function d(a){l=a.exports;if(l.memory){a=l.memory;var b=c.buffer;a.byteLength<b.byteLength&&c.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;qa()}c.asm=l;c.usingWasm=!0;M--;c.monitorRunDependencies&&c.monitorRunDependencies(M);0==M&&(null!==Da&&(clearInterval(Da),Da=null),N&&(a=N,N=null,a()))}
function e(a){d(a.instance)}function y(a){b().then(function(a){return WebAssembly.instantiate(a,f)}).then(a).catch(function(a){c.printErr("failed to asynchronously prepare wasm: "+a);F(a)})}if("object"!==typeof WebAssembly)return c.printErr("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return c.printErr("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;f.global={NaN:NaN,Infinity:Infinity};f["global.Math"]=Math;f.env=a;M++;c.monitorRunDependencies&&c.monitorRunDependencies(M);
if(c.instantiateWasm)try{return c.instantiateWasm(f,d)}catch(La){return c.printErr("Module.instantiateWasm callback failed with error: "+La),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||O(h)||"function"!==typeof fetch?y(e):WebAssembly.instantiateStreaming(fetch(h,{credentials:"same-origin"}),f).then(e).catch(function(a){c.printErr("wasm streaming compile failed: "+a);c.printErr("falling back to ArrayBuffer instantiation");y(e)});return{}}var d="asm2wasm_linpack_double.c.wast",
h="asm2wasm_linpack_double.c.wasm",k="asm2wasm_linpack_double.c.temp.asm.js";"function"===typeof c.locateFile&&(O(d)||(d=c.locateFile(d)),O(h)||(h=c.locateFile(h)),O(k)||(k=c.locateFile(k)));var f={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:c},l=null;c.asmPreload=c.asm;var t=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===u)var b=t(a);else a:{var d=c.usingWasm?65536:16777216;0<a%d&&(a+=d-a%d);d=c.buffer.byteLength;if(c.usingWasm)try{b=
-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(y){b=null;break a}b=void 0}return b};var u="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var d=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=b.table}b.memoryBase||(b.memoryBase=c.STATIC_BASE);
b.tableBase||(b.tableBase=0);(b=e(b))||F("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();I=1024;B=I+6016;wa.push();c.STATIC_BASE=I;c.STATIC_BUMP=6016;B+=16;var P=0;function Q(){P+=4;return D[P-4>>2]}var Ea={};
function R(a,b){P=b;try{var e=Q(),d=Q(),h=Q();a=0;R.j||(R.j=[null,[],[]],R.u=function(a,b){var d=R.j[a];assert(d);0===b||10===b?((1===a?c.print:c.printErr)(ka(d,0)),d.length=0):d.push(b)});for(b=0;b<h;b++){for(var k=D[d+8*b>>2],f=D[d+(8*b+4)>>2],l=0;l<f;l++)R.u(e,H[k+l]);a+=f}return a}catch(t){return"undefined"!==typeof FS&&t instanceof FS.i||F(t),-t.l}}function S(){void 0===S.start&&(S.start=Date.now());return 1E3*(Date.now()-S.start)|0}var T=B;B+=48;fa(U("GMT"),2);var V=B,Fa=B+=16,Ga=B+=16;B+=16;
function Ha(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Ia){Ia=!0;D[Ga>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),e=new Date(2E3,6,1);D[Fa>>2]=Number(b.getTimezoneOffset()!=e.getTimezoneOffset());var d=a(b),h=a(e);d=fa(U(d),0);h=fa(U(h),0);e.getTimezoneOffset()<b.getTimezoneOffset()?(D[V>>2]=d,D[V+4>>2]=h):(D[V>>2]=h,D[V+4>>2]=d)}}var Ia;function W(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Ja(a,b){for(var e=0,d=0;d<=b;e+=a[d++]);return e}var X=[31,29,31,30,31,30,31,31,30,31,30,31],Y=[31,28,31,30,31,30,31,31,30,31,30,31];function Z(a,b){for(a=new Date(a.getTime());0<b;){var e=a.getMonth(),d=(W(a.getFullYear())?X:Y)[e];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>e?a.setMonth(e+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}C=A(4);ra=J=da(B);sa=ra+ua;ta=da(sa);D[C>>2]=ta;aa=!0;
function U(a,b){var e=Array(na(a)+1);a=ma(a,e,0,e.length);b&&(e.length=a);return e}c.wasmTableSize=6;c.wasmMaxTableSize=6;c.o={};
c.s={abort:F,enlargeMemory:function(){ca()},getTotalMemory:function(){return E},abortOnCannotGrowMemory:ca,___setErrNo:function(a){c.___errno_location&&(D[c.___errno_location()>>2]=a);return a},___syscall140:function(a,b){P=b;try{var e=Ea.v();Q();var d=Q(),h=Q(),k=Q();FS.G(e,d,k);D[h>>2]=e.position;e.w&&0===d&&0===k&&(e.w=null);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof FS.i||F(f),-f.l}},___syscall146:R,___syscall54:function(a,b){P=b;return 0},___syscall6:function(a,b){P=b;try{var e=
Ea.v();FS.close(e);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.i||F(d),-d.l}},_clock:S,_emscripten_memcpy_big:function(a,b,e){H.set(H.subarray(b,b+e),a);return a},_localtime:function(a){Ha();a=new Date(1E3*D[a>>2]);D[T>>2]=a.getSeconds();D[T+4>>2]=a.getMinutes();D[T+8>>2]=a.getHours();D[T+12>>2]=a.getDate();D[T+16>>2]=a.getMonth();D[T+20>>2]=a.getFullYear()-1900;D[T+24>>2]=a.getDay();var b=new Date(a.getFullYear(),0,1);D[T+28>>2]=(a.getTime()-b.getTime())/864E5|0;D[T+36>>2]=-(60*
a.getTimezoneOffset());var e=(new Date(2E3,6,1)).getTimezoneOffset();b=b.getTimezoneOffset();a=(e!=b&&a.getTimezoneOffset()==Math.min(b,e))|0;D[T+32>>2]=a;D[T+40>>2]=D[V+(a?4:0)>>2];return T},_strftime:function(a,b,e,d){function h(a,b,d){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=d[0]+a;return a}function k(a,b){return h(a,b,"0")}function f(a,b){function d(a){return 0>a?-1:0<a?1:0}var y;0===(y=d(a.getFullYear()-b.getFullYear()))&&0===(y=d(a.getMonth()-b.getMonth()))&&(y=d(a.getDate()-
b.getDate()));return y}function l(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function t(a){a=Z(new Date(a.a+1900,0,1),a.g);var b=l(new Date(a.getFullYear()+1,0,4));return 0>=f(l(new Date(a.getFullYear(),0,4)),a)?0>=f(b,a)?a.getFullYear()+
1:a.getFullYear():a.getFullYear()-1}var u=D[d+40>>2];d={C:D[d>>2],B:D[d+4>>2],f:D[d+8>>2],c:D[d+12>>2],b:D[d+16>>2],a:D[d+20>>2],m:D[d+24>>2],g:D[d+28>>2],H:D[d+32>>2],A:D[d+36>>2],D:u?ja(u):""};e=ja(e);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var n in u)e=e.replace(new RegExp(n,"g"),u[n]);var Aa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ba="January February March April May June July August September October November December".split(" ");
u={"%a":function(a){return Aa[a.m].substring(0,3)},"%A":function(a){return Aa[a.m]},"%b":function(a){return Ba[a.b].substring(0,3)},"%B":function(a){return Ba[a.b]},"%C":function(a){return k((a.a+1900)/100|0,2)},"%d":function(a){return k(a.c,2)},"%e":function(a){return h(a.c,2," ")},"%g":function(a){return t(a).toString().substring(2)},"%G":function(a){return t(a)},"%H":function(a){return k(a.f,2)},"%I":function(a){a=a.f;0==a?a=12:12<a&&(a-=12);return k(a,2)},"%j":function(a){return k(a.c+Ja(W(a.a+
1900)?X:Y,a.b-1),3)},"%m":function(a){return k(a.b+1,2)},"%M":function(a){return k(a.B,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.f&&12>a.f?"AM":"PM"},"%S":function(a){return k(a.C,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.a+1900,a.b+1,a.c,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.a+1900,0,1),d=0===b.getDay()?b:Z(b,7-b.getDay());a=new Date(a.a+1900,a.b,a.c);return 0>f(d,a)?k(Math.ceil((31-d.getDate()+(Ja(W(a.getFullYear())?X:Y,a.getMonth()-
1)-31)+a.getDate())/7),2):0===f(d,b)?"01":"00"},"%V":function(a){var b=l(new Date(a.a+1900,0,4)),d=l(new Date(a.a+1901,0,4)),e=Z(new Date(a.a+1900,0,1),a.g);return 0>f(e,b)?"53":0>=f(d,e)?"01":k(Math.ceil((b.getFullYear()<a.a+1900?a.g+32-b.getDate():a.g+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.a+1900,a.b+1,a.c,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.a,0,1),d=1===b.getDay()?b:Z(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.a+1900,a.b,a.c);return 0>f(d,a)?k(Math.ceil((31-
d.getDate()+(Ja(W(a.getFullYear())?X:Y,a.getMonth()-1)-31)+a.getDate())/7),2):0===f(d,b)?"01":"00"},"%y":function(a){return(a.a+1900).toString().substring(2)},"%Y":function(a){return a.a+1900},"%z":function(a){a=a.A;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.D},"%%":function(){return"%"}};for(n in u)0<=e.indexOf(n)&&(e=e.replace(new RegExp(n,"g"),u[n](d)));n=U(e,!1);if(n.length>b)return 0;G.set(n,a);return n.length-1},_time:function(a){var b=
Date.now()/1E3|0;a&&(D[a>>2]=b);return b},DYNAMICTOP_PTR:C,STACKTOP:J};var Ka=c.asm(c.o,c.s,buffer);c.asm=Ka;c._main=function(){return c.asm._main.apply(null,arguments)};var ha=c._malloc=function(){return c.asm._malloc.apply(null,arguments)},ia=c.stackAlloc=function(){return c.asm.stackAlloc.apply(null,arguments)};c.asm=Ka;function z(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}z.prototype=Error();z.prototype.constructor=z;
N=function Ma(){c.calledRun||Na([].concat(c.arguments));c.calledRun||(N=Ma)};c.callMain=function(a){a=a||[];L||(L=!0,K(wa));var b=a.length+1,e=ia(4*(b+1));D[e>>2]=oa(c.thisProgram);for(var d=1;d<b;d++)D[(e>>2)+d]=oa(a[d-1]);D[(e>>2)+b]=0;try{var h=c._main(b,e,0);Oa(h,!0)}catch(k){k instanceof z||("SimulateInfiniteLoop"==k?c.noExitRuntime=!0:((a=k)&&"object"===typeof k&&k.stack&&(a=[k,k.stack]),c.printErr("exception thrown: "+a),c.quit(1,k)))}finally{}};
function Na(a){function b(){if(!c.calledRun&&(c.calledRun=!0,!ea)){L||(L=!0,K(wa));K(xa);if(c.onRuntimeInitialized)c.onRuntimeInitialized();c._main&&Pa&&c.callMain(a);if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var b=c.postRun.shift();za.unshift(b)}K(za)}}a=a||c.arguments;if(!(0<M)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ca();K(va);0<M||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);b()},1)):b())}}c.run=Na;function Oa(a,b){if(!b||!c.noExitRuntime||0!==a){if(!c.noExitRuntime&&(ea=!0,J=void 0,K(ya),c.onExit))c.onExit(a);r&&process.exit(a);c.quit(a,new z(a))}}c.exit=Oa;function F(a){if(c.onAbort)c.onAbort(a);void 0!==a?(c.print(a),c.printErr(a),a=JSON.stringify(a)):a="";ea=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=F;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var Pa=!0;
c.noInitialRun&&(Pa=!1);c.noExitRuntime=!0;Na([].concat(c.arguments));
