var a;a||(a=typeof Module !== 'undefined' ? Module : {});var k={},m;for(m in a)a.hasOwnProperty(m)&&(k[m]=a[m]);a.arguments=[];a.thisProgram="./this.program";a.quit=function(b,c){throw c;};a.preRun=[];a.postRun=[];var n=!1,q=!1,r=!1,t=!1;
if(a.ENVIRONMENT)if("WEB"===a.ENVIRONMENT)n=!0;else if("WORKER"===a.ENVIRONMENT)q=!0;else if("NODE"===a.ENVIRONMENT)r=!0;else if("SHELL"===a.ENVIRONMENT)t=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else n="object"===typeof window,q="function"===typeof importScripts,r="object"===typeof process&&"function"===typeof require&&!n&&!q,t=!n&&!r&&!q;
if(r){var u,v;a.read=function(b,c){u||(u=require("fs"));v||(v=require("path"));b=v.normalize(b);b=u.readFileSync(b);return c?b:b.toString()};a.readBinary=function(b){b=a.read(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);return b};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(b){if(!(b instanceof w))throw b;});process.on("unhandledRejection",
function(){process.exit(1)});a.inspect=function(){return"[Emscripten Module object]"}}else if(t)"undefined"!=typeof read&&(a.read=function(b){return read(b)}),a.readBinary=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");assert("object"===typeof b);return b},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=arguments),"function"===typeof quit&&(a.quit=function(b){quit(b)});else if(n||q)a.read=function(b){var c=
new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},q&&(a.readBinary=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),a.readAsync=function(b,c,d){var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)},"undefined"!=typeof arguments&&(a.arguments=arguments),a.setWindowTitle=
function(b){document.title=b};a.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;a.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||a.print;a.print=a.print;a.printErr=a.printErr;for(m in k)k.hasOwnProperty(m)&&(a[m]=k[m]);k=void 0;function aa(b){var c;c||(c=16);return Math.ceil(b/c)*c}var x=0;function assert(b,c){b||y("Assertion failed: "+c)}
var ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function ca(b){for(var c=0,d=0;d<b.length;++d){var e=b.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|b.charCodeAt(++d)&1023);127>=e?++c:c=2047>=e?c+2:65535>=e?c+3:2097151>=e?c+4:67108863>=e?c+5:c+6}var g=c+1;c=da(g);d=c;e=ea;if(0<g){g=d+g-1;for(var h=0;h<b.length;++h){var f=b.charCodeAt(h);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|b.charCodeAt(++h)&1023);if(127>=f){if(d>=g)break;e[d++]=f}else{if(2047>=f){if(d+1>=g)break;e[d++]=192|f>>6}else{if(65535>=f){if(d+2>=g)break;e[d++]=224|f>>
12}else{if(2097151>=f){if(d+3>=g)break;e[d++]=240|f>>18}else{if(67108863>=f){if(d+4>=g)break;e[d++]=248|f>>24}else{if(d+5>=g)break;e[d++]=252|f>>30;e[d++]=128|f>>24&63}e[d++]=128|f>>18&63}e[d++]=128|f>>12&63}e[d++]=128|f>>6&63}e[d++]=128|f&63}}e[d]=0}return c}var buffer,ea,z,fa,A;
function ha(){a.HEAP8=ea=new Int8Array(buffer);a.HEAP16=fa=new Int16Array(buffer);a.HEAP32=A=new Int32Array(buffer);a.HEAPU8=z=new Uint8Array(buffer);a.HEAPU16=new Uint16Array(buffer);a.HEAPU32=new Uint32Array(buffer);a.HEAPF32=new Float32Array(buffer);a.HEAPF64=new Float64Array(buffer)}var B,C,D,E,F,G,H,I;B=C=E=F=G=H=I=0;D=!1;
function ia(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+J+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var K=a.TOTAL_STACK||5242880,J=a.TOTAL_MEMORY||268435456;J<K&&a.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+J+"! (TOTAL_STACK="+K+")");
a.buffer?buffer=a.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(a.wasmMemory=new WebAssembly.Memory({initial:J/65536,maximum:J/65536}),buffer=a.wasmMemory.buffer):buffer=new ArrayBuffer(J),a.buffer=buffer);ha();A[0]=1668509029;fa[1]=25459;if(115!==z[2]||99!==z[3])throw"Runtime error: expected the system to be little-endian!";
function M(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c();else{var d=c.m;"number"===typeof d?void 0===c.b?a.dynCall_v(d):a.dynCall_vi(d,c.b):d(void 0===c.b?null:c.b)}}}var ja=[],N=[],ka=[],la=[],ma=[],O=!1;function na(){var b=a.preRun.shift();ja.unshift(b)}var P=0,Q=null,R=null;a.preloadedImages={};a.preloadedAudios={};function S(b){return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}
(function(){function b(){try{if(a.wasmBinary)return new Uint8Array(a.wasmBinary);if(a.readBinary)return a.readBinary(g);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(L){y(L)}}function c(){return a.wasmBinary||!n&&!q||"function"!==typeof fetch?new Promise(function(c){c(b())}):fetch(g,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+g+
"'";return b.arrayBuffer()}).catch(function(){return b()})}function d(b){function d(b){l=b.exports;if(l.memory){b=l.memory;var c=a.buffer;b.byteLength<c.byteLength&&a.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(b)).set(c);a.buffer=buffer=b;ha()}a.asm=l;a.usingWasm=!0;P--;a.monitorRunDependencies&&a.monitorRunDependencies(P);0==P&&(null!==Q&&(clearInterval(Q),Q=null),R&&(b=R,R=null,b()))}function e(b){d(b.instance)}
function L(b){c().then(function(b){return WebAssembly.instantiate(b,f)}).then(b).catch(function(b){a.printErr("failed to asynchronously prepare wasm: "+b);y(b)})}if("object"!==typeof WebAssembly)return a.printErr("no native wasm support detected"),!1;if(!(a.wasmMemory instanceof WebAssembly.Memory))return a.printErr("no native wasm Memory in use"),!1;b.memory=a.wasmMemory;f.global={NaN:NaN,Infinity:Infinity};f["global.Math"]=Math;f.env=b;P++;a.monitorRunDependencies&&a.monitorRunDependencies(P);if(a.instantiateWasm)try{return a.instantiateWasm(f,
d)}catch(ua){return a.printErr("Module.instantiateWasm callback failed with error: "+ua),!1}a.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||S(g)||"function"!==typeof fetch?L(e):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),f).then(e).catch(function(b){a.printErr("wasm streaming compile failed: "+b);a.printErr("falling back to ArrayBuffer instantiation");L(e)});return{}}var e="wasm_havlak.wast",g="wasm_havlak.wasm",h="wasm_havlak.temp.asm.js";"function"===
typeof a.locateFile&&(S(e)||(e=a.locateFile(e)),S(g)||(g=a.locateFile(g)),S(h)||(h=a.locateFile(h)));var f={global:null,env:null,asm2wasm:{"f64-rem":function(b,c){return b%c},"debugger":function(){debugger}},parent:a},l=null;a.asmPreload=a.asm;var p=a.reallocBuffer;a.reallocBuffer=function(b){if("asmjs"===Z)var c=p(b);else a:{var d=a.usingWasm?65536:16777216;0<b%d&&(b+=d-b%d);d=a.buffer.byteLength;if(a.usingWasm)try{c=-1!==a.wasmMemory.grow((b-d)/65536)?a.buffer=a.wasmMemory.buffer:null;break a}catch(ya){c=
null;break a}c=void 0}return c};var Z="";a.asm=function(b,c){if(!c.table){b=a.wasmTableSize;void 0===b&&(b=1024);var e=a.wasmMaxTableSize;c.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:b,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:b,element:"anyfunc"}):Array(b);a.wasmTable=c.table}c.memoryBase||(c.memoryBase=a.STATIC_BASE);c.tableBase||(c.tableBase=0);(c=d(c))||y("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");
return c}})();B=1024;C=B+7088;N.push();a.STATIC_BASE=B;a.STATIC_BUMP=7088;C+=16;function T(){return!!T.a}var U=0;function V(){U+=4;return A[U-4>>2]}var oa={};
function W(b,c){U=c;try{var d=V(),e=V(),g=V();b=0;W.a||(W.a=[null,[],[]],W.i=function(b,c){var d=W.a[b];assert(d);if(0===c||10===c){b=1===b?a.print:a.printErr;a:{for(var e=c=0;d[e];)++e;if(16<e-c&&d.subarray&&ba)c=ba.decode(d.subarray(c,e));else for(e="";;){var f=d[c++];if(!f){c=e;break a}if(f&128){var g=d[c++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var h=d[c++]&63;if(224==(f&240))f=(f&15)<<12|g<<6|h;else{var l=d[c++]&63;if(240==(f&248))f=(f&7)<<18|g<<12|h<<6|l;else{var p=d[c++]&
63;if(248==(f&252))f=(f&3)<<24|g<<18|h<<12|l<<6|p;else{var Z=d[c++]&63;f=(f&1)<<30|g<<24|h<<18|l<<12|p<<6|Z}}}65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}}b(c);d.length=0}else d.push(c)});for(c=0;c<g;c++){for(var h=A[e+8*c>>2],f=A[e+(8*c+4)>>2],l=0;l<f;l++)W.i(d,z[h+l]);b+=f}return b}catch(p){return"undefined"!==typeof FS&&p instanceof FS.c||y(p),-p.f}}var X={},pa=1;
function Y(b,c){Y.a||(Y.a={});b in Y.a||(a.dynCall_v(c),Y.a[b]=1)}assert(!D);var qa=C;C=C+4+15&-16;I=qa;E=F=aa(C);G=E+K;H=aa(G);A[I>>2]=H;D=!0;a.wasmTableSize=44;a.wasmMaxTableSize=44;a.g={};
a.h={abort:y,enlargeMemory:function(){ia()},getTotalMemory:function(){return J},abortOnCannotGrowMemory:ia,___cxa_allocate_exception:function(b){return ra(b)},___cxa_throw:function(b){"uncaught_exception"in T?T.a++:T.a=1;throw b+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},___setErrNo:function(b){a.___errno_location&&(A[a.___errno_location()>>2]=b);return b},___syscall140:function(b,c){U=
c;try{var d=oa.j();V();var e=V(),g=V(),h=V();FS.o(d,e,h);A[g>>2]=d.position;d.l&&0===e&&0===h&&(d.l=null);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof FS.c||y(f),-f.f}},___syscall146:W,___syscall54:function(b,c){U=c;return 0},___syscall6:function(b,c){U=c;try{var d=oa.j();FS.close(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.c||y(e),-e.f}},_abort:function(){a.abort()},_emscripten_memcpy_big:function(b,c,d){z.set(z.subarray(c,c+d),b);return b},_pthread_getspecific:function(b){return X[b]||
0},_pthread_key_create:function(b){if(0==b)return 22;A[b>>2]=pa;X[pa]=0;pa++;return 0},_pthread_once:Y,_pthread_setspecific:function(b,c){if(!(b in X))return 22;X[b]=c;return 0},DYNAMICTOP_PTR:I,STACKTOP:F};var sa=a.asm(a.g,a.h,buffer);a.asm=sa;a._main=function(){return a.asm._main.apply(null,arguments)};var ra=a._malloc=function(){return a.asm._malloc.apply(null,arguments)},da=a.stackAlloc=function(){return a.asm.stackAlloc.apply(null,arguments)};
a.dynCall_v=function(){return a.asm.dynCall_v.apply(null,arguments)};a.dynCall_vi=function(){return a.asm.dynCall_vi.apply(null,arguments)};a.asm=sa;function w(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}w.prototype=Error();w.prototype.constructor=w;R=function ta(){a.calledRun||va([].concat(a.arguments));a.calledRun||(R=ta)};
a.callMain=function(b){b=b||[];O||(O=!0,M(N));var c=b.length+1,d=da(4*(c+1));A[d>>2]=ca(a.thisProgram);for(var e=1;e<c;e++)A[(d>>2)+e]=ca(b[e-1]);A[(d>>2)+c]=0;try{var g=a._main(c,d,0);wa(g,!0)}catch(h){h instanceof w||("SimulateInfiniteLoop"==h?a.noExitRuntime=!0:((b=h)&&"object"===typeof h&&h.stack&&(b=[h,h.stack]),a.printErr("exception thrown: "+b),a.quit(1,h)))}finally{}};
function va(b){function c(){if(!a.calledRun&&(a.calledRun=!0,!x)){O||(O=!0,M(N));M(ka);if(a.onRuntimeInitialized)a.onRuntimeInitialized();a._main&&xa&&a.callMain(b);if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();ma.unshift(c)}M(ma)}}b=b||a.arguments;if(!(0<P)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)na();M(ja);0<P||a.calledRun||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},
1);c()},1)):c())}}a.run=va;function wa(b,c){if(!c||!a.noExitRuntime||0!==b){if(!a.noExitRuntime&&(x=!0,F=void 0,M(la),a.onExit))a.onExit(b);r&&process.exit(b);a.quit(b,new w(b))}}a.exit=wa;function y(b){if(a.onAbort)a.onAbort(b);void 0!==b?(a.print(b),a.printErr(b),b=JSON.stringify(b)):b="";x=!0;throw"abort("+b+"). Build with -s ASSERTIONS=1 for more info.";}a.abort=y;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();var xa=!0;
a.noInitialRun&&(xa=!1);a.noExitRuntime=!0;va([].concat(a.arguments));
