var a;a||(a=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in a)a.hasOwnProperty(l)&&(k[l]=a[l]);a.arguments=[];a.thisProgram="./this.program";a.quit=function(b,c){throw c;};a.preRun=[];a.postRun=[];var m=!1,n=!1,p=!1,q=!1;
if(a.ENVIRONMENT)if("WEB"===a.ENVIRONMENT)m=!0;else if("WORKER"===a.ENVIRONMENT)n=!0;else if("NODE"===a.ENVIRONMENT)p=!0;else if("SHELL"===a.ENVIRONMENT)q=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else m="object"===typeof window,n="function"===typeof importScripts,p="object"===typeof process&&"function"===typeof require&&!m&&!n,q=!m&&!p&&!n;
if(p){var r,t;a.read=function(b,c){r||(r=require("fs"));t||(t=require("path"));b=t.normalize(b);b=r.readFileSync(b);return c?b:b.toString()};a.readBinary=function(b){b=a.read(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);return b};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(b){if(!(b instanceof u))throw b;});process.on("unhandledRejection",
function(){process.exit(1)});a.inspect=function(){return"[Emscripten Module object]"}}else if(q)"undefined"!=typeof read&&(a.read=function(b){return read(b)}),a.readBinary=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");assert("object"===typeof b);return b},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=arguments),"function"===typeof quit&&(a.quit=function(b){quit(b)});else if(m||n)a.read=function(b){var c=
new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},n&&(a.readBinary=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),a.readAsync=function(b,c,e){var d=new XMLHttpRequest;d.open("GET",b,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?c(d.response):e()};d.onerror=e;d.send(null)},a.setWindowTitle=function(b){document.title=b};
a.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;a.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||a.print;a.print=a.print;a.printErr=a.printErr;for(l in k)k.hasOwnProperty(l)&&(a[l]=k[l]);k=void 0;function v(b){var c;c||(c=16);return Math.ceil(b/c)*c}var w=0;function assert(b,c){b||x("Assertion failed: "+c)}"undefined"!==typeof TextDecoder&&new TextDecoder("utf8");
"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function y(b){for(var c=0,e=0;e<b.length;++e){var d=b.charCodeAt(e);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|b.charCodeAt(++e)&1023);127>=d?++c:c=2047>=d?c+2:65535>=d?c+3:2097151>=d?c+4:67108863>=d?c+5:c+6}var g=c+1;c=z(g);e=c;d=A;if(0<g){g=e+g-1;for(var h=0;h<b.length;++h){var f=b.charCodeAt(h);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|b.charCodeAt(++h)&1023);if(127>=f){if(e>=g)break;d[e++]=f}else{if(2047>=f){if(e+1>=g)break;d[e++]=192|f>>6}else{if(65535>=f){if(e+2>=g)break;d[e++]=224|f>>12}else{if(2097151>=
f){if(e+3>=g)break;d[e++]=240|f>>18}else{if(67108863>=f){if(e+4>=g)break;d[e++]=248|f>>24}else{if(e+5>=g)break;d[e++]=252|f>>30;d[e++]=128|f>>24&63}d[e++]=128|f>>18&63}d[e++]=128|f>>12&63}d[e++]=128|f>>6&63}d[e++]=128|f&63}}d[e]=0}return c}var buffer,A,B,C,D;
function E(){a.HEAP8=A=new Int8Array(buffer);a.HEAP16=C=new Int16Array(buffer);a.HEAP32=D=new Int32Array(buffer);a.HEAPU8=B=new Uint8Array(buffer);a.HEAPU16=new Uint16Array(buffer);a.HEAPU32=new Uint32Array(buffer);a.HEAPF32=new Float32Array(buffer);a.HEAPF64=new Float64Array(buffer)}var F,H,I,J,K,L,M,N;F=H=J=K=L=M=N=0;I=!1;var O=a.TOTAL_STACK||5242880,P=a.TOTAL_MEMORY||268435456;P<O&&a.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+P+"! (TOTAL_STACK="+O+")");
a.buffer?buffer=a.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(a.wasmMemory=new WebAssembly.Memory({initial:P/65536,maximum:P/65536}),buffer=a.wasmMemory.buffer):buffer=new ArrayBuffer(P),a.buffer=buffer);E();D[0]=1668509029;C[1]=25459;if(115!==B[2]||99!==B[3])throw"Runtime error: expected the system to be little-endian!";
function Q(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c();else{var e=c.f;"number"===typeof e?void 0===c.a?a.dynCall_v(e):a.dynCall_vi(e,c.a):e(void 0===c.a?null:c.a)}}}var R=[],S=[],aa=[],ba=[],T=[],U=!1;function ca(){var b=a.preRun.shift();R.unshift(b)}var V=0,W=null,X=null;a.preloadedImages={};a.preloadedAudios={};function Y(b){return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}
(function(){function b(){try{if(a.wasmBinary)return new Uint8Array(a.wasmBinary);if(a.readBinary)return a.readBinary(g);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(ha){x(ha)}}function c(){return a.wasmBinary||!m&&!n||"function"!==typeof fetch?new Promise(function(c){c(b())}):fetch(g,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+
g+"'";return b.arrayBuffer()}).catch(function(){return b()})}function e(b){function e(b){G=b.exports;if(G.memory){b=G.memory;var c=a.buffer;b.byteLength<c.byteLength&&a.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(b)).set(c);a.buffer=buffer=b;E()}a.asm=G;a.usingWasm=!0;K=J+O;L=J;a.asm.stackRestore(K);V--;a.monitorRunDependencies&&a.monitorRunDependencies(V);0==V&&(null!==W&&(clearInterval(W),
W=null),X&&(b=X,X=null,b()))}function d(b){e(b.instance)}function h(b){c().then(function(b){return WebAssembly.instantiate(b,f)}).then(b).catch(function(b){a.printErr("failed to asynchronously prepare wasm: "+b);x(b)})}if("object"!==typeof WebAssembly)return a.printErr("no native wasm support detected"),!1;if(!(a.wasmMemory instanceof WebAssembly.Memory))return a.printErr("no native wasm Memory in use"),!1;b.memory=a.wasmMemory;f.global={NaN:NaN,Infinity:Infinity};f["global.Math"]=Math;f.env=b;V++;
a.monitorRunDependencies&&a.monitorRunDependencies(V);if(a.instantiateWasm)try{return a.instantiateWasm(f,e)}catch(ia){return a.printErr("Module.instantiateWasm callback failed with error: "+ia),!1}a.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Y(g)||"function"!==typeof fetch?h(d):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),f).then(d).catch(function(b){a.printErr("wasm streaming compile failed: "+b);a.printErr("falling back to ArrayBuffer instantiation");
h(d)});return{}}var d="wasmbackend_primes-nocheck.wast",g="wasmbackend_primes-nocheck.wasm",h="wasmbackend_primes-nocheck.temp.asm.js";"function"===typeof a.locateFile&&(Y(d)||(d=a.locateFile(d)),Y(g)||(g=a.locateFile(g)),Y(h)||(h=a.locateFile(h)));var f={global:null,env:null,asm2wasm:{"f64-rem":function(b,c){return b%c},"debugger":function(){debugger}},parent:a},G=null;a.asmPreload=a.asm;var ja=a.reallocBuffer;a.reallocBuffer=function(b){if("asmjs"===ka)var c=ja(b);else a:{var d=a.usingWasm?65536:
16777216;0<b%d&&(b+=d-b%d);d=a.buffer.byteLength;if(a.usingWasm)try{c=-1!==a.wasmMemory.grow((b-d)/65536)?a.buffer=a.wasmMemory.buffer:null;break a}catch(na){c=null;break a}c=void 0}return c};var ka="";a.asm=function(b,c){b={};for(var d in c){var f=d;"_"==f[0]&&(f=f.substr(1));b[f]=c[d]}c=b;c.table||(d=a.wasmTableSize,void 0===d&&(d=1024),b=a.wasmMaxTableSize,c.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==b?new WebAssembly.Table({initial:d,maximum:b,element:"anyfunc"}):
new WebAssembly.Table({initial:d,element:"anyfunc"}):Array(d),a.wasmTable=c.table);c.memoryBase||(c.memoryBase=a.STATIC_BASE);c.tableBase||(c.tableBase=0);(d=e(c))||x("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return d}})();F=1024;H=F+512;S.push();a.STATIC_BASE=F;a.STATIC_BUMP=512;H+=16;assert(!I);var da=H;H=H+4+15&-16;N=da;J=K=v(H);L=J+O;M=v(L);D[N>>2]=M;I=!0;a.b={};
a.c={};var ea=a.asm(a.b,a.c,buffer);a.asm=ea;a._stackRestore=function(){return a.asm.stackRestore.apply(null,arguments)};a._stackAlloc=function(){return a.asm.stackAlloc.apply(null,arguments)};a._main=function(){return a.asm.main.apply(null,arguments)};var z=a._stackAlloc;a.asm=ea;function u(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}u.prototype=Error();u.prototype.constructor=u;
X=function fa(){a.calledRun||Z([].concat(a.arguments));a.calledRun||(X=fa)};a.callMain=function(b){b=b||[];U||(U=!0,Q(S));var c=b.length+1,e=z(4*(c+1));D[e>>2]=y(a.thisProgram);for(var d=1;d<c;d++)D[(e>>2)+d]=y(b[d-1]);D[(e>>2)+c]=0;try{var g=a._main(c,e,0);la(g,!0)}catch(h){h instanceof u||("SimulateInfiniteLoop"==h?a.noExitRuntime=!0:((b=h)&&"object"===typeof h&&h.stack&&(b=[h,h.stack]),a.printErr("exception thrown: "+b),a.quit(1,h)))}finally{}};
function Z(b){function c(){if(!a.calledRun&&(a.calledRun=!0,!w)){U||(U=!0,Q(S));Q(aa);if(a.onRuntimeInitialized)a.onRuntimeInitialized();a._main&&ma&&a.callMain(b);if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();T.unshift(c)}Q(T)}}b=b||a.arguments;if(!(0<V)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ca();Q(R);0<V||a.calledRun||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},
1);c()},1)):c())}}a.run=Z;function la(b,c){if(!c||!a.noExitRuntime||0!==b){if(!a.noExitRuntime&&(w=!0,K=void 0,Q(ba),a.onExit))a.onExit(b);p&&process.exit(b);a.quit(b,new u(b))}}a.exit=la;function x(b){if(a.onAbort)a.onAbort(b);void 0!==b?(a.print(b),a.printErr(b),b=JSON.stringify(b)):b="";w=!0;throw"abort("+b+"). Build with -s ASSERTIONS=1 for more info.";}a.abort=x;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();var ma=!0;
a.noInitialRun&&(ma=!1);a.noExitRuntime=!0;Z([].concat(a.arguments));
