var b;b||(b=typeof Module !== 'undefined' ? Module : {});var l={},n;for(n in b)b.hasOwnProperty(n)&&(l[n]=b[n]);b.arguments=[];b.thisProgram="./this.program";b.quit=function(a,c){throw c;};b.preRun=[];b.postRun=[];var r=!1,t=!1,u=!1,aa=!1;
if(b.ENVIRONMENT)if("WEB"===b.ENVIRONMENT)r=!0;else if("WORKER"===b.ENVIRONMENT)t=!0;else if("NODE"===b.ENVIRONMENT)u=!0;else if("SHELL"===b.ENVIRONMENT)aa=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else r="object"===typeof window,t="function"===typeof importScripts,u="object"===typeof process&&"function"===typeof require&&!r&&!t,aa=!r&&!u&&!t;
if(u){var ba,ca;b.read=function(a,c){ba||(ba=require("fs"));ca||(ca=require("path"));a=ca.normalize(a);a=ba.readFileSync(a);return c?a:a.toString()};b.readBinary=function(a){a=b.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(b.thisProgram=process.argv[1].replace(/\\/g,"/"));b.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=b);process.on("uncaughtException",function(a){if(!(a instanceof w))throw a;});process.on("unhandledRejection",
function(){process.exit(1)});b.inspect=function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(b.read=function(a){return read(a)}),b.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?b.arguments=scriptArgs:"undefined"!=typeof arguments&&(b.arguments=arguments),"function"===typeof quit&&(b.quit=function(a){quit(a)});else if(r||t)b.read=function(a){var c=
new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},t&&(b.readBinary=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),b.readAsync=function(a,c,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)},b.setWindowTitle=function(a){document.title=a};
b.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;b.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||b.print;b.print=b.print;b.printErr=b.printErr;for(n in l)l.hasOwnProperty(n)&&(b[n]=l[n]);l=void 0;function da(a){var c;c||(c=16);return Math.ceil(a/c)*c}function ea(a){x||(x={});x[a]||(x[a]=1,b.printErr(a))}var x,y=0;function assert(a,c){a||z("Assertion failed: "+c)}
var fa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function ha(a){for(var c=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++c:c=2047>=e?c+2:65535>=e?c+3:2097151>=e?c+4:67108863>=e?c+5:c+6}var f=c+1;c=ia(f);d=c;e=ja;if(0<f){f=d+f-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(d>=f)break;e[d++]=h}else{if(2047>=h){if(d+1>=f)break;e[d++]=192|h>>6}else{if(65535>=h){if(d+2>=f)break;e[d++]=224|h>>
12}else{if(2097151>=h){if(d+3>=f)break;e[d++]=240|h>>18}else{if(67108863>=h){if(d+4>=f)break;e[d++]=248|h>>24}else{if(d+5>=f)break;e[d++]=252|h>>30;e[d++]=128|h>>24&63}e[d++]=128|h>>18&63}e[d++]=128|h>>12&63}e[d++]=128|h>>6&63}e[d++]=128|h&63}}e[d]=0}return c}var buffer,ja,A,ka,B,la;
function ma(){b.HEAP8=ja=new Int8Array(buffer);b.HEAP16=ka=new Int16Array(buffer);b.HEAP32=B=new Int32Array(buffer);b.HEAPU8=A=new Uint8Array(buffer);b.HEAPU16=new Uint16Array(buffer);b.HEAPU32=la=new Uint32Array(buffer);b.HEAPF32=new Float32Array(buffer);b.HEAPF64=new Float64Array(buffer)}var C,D,na,oa,E,pa,qa,F;C=D=oa=E=pa=qa=F=0;na=!1;
function ra(){z("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+G+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var sa=b.TOTAL_STACK||5242880,G=b.TOTAL_MEMORY||268435456;G<sa&&b.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+G+"! (TOTAL_STACK="+sa+")");
b.buffer?buffer=b.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(b.wasmMemory=new WebAssembly.Memory({initial:G/65536,maximum:G/65536}),buffer=b.wasmMemory.buffer):buffer=new ArrayBuffer(G),b.buffer=buffer);ma();B[0]=1668509029;ka[1]=25459;if(115!==A[2]||99!==A[3])throw"Runtime error: expected the system to be little-endian!";
function H(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c();else{var d=c.m;"number"===typeof d?void 0===c.a?b.dynCall_v(d):b.dynCall_vi(d,c.a):d(void 0===c.a?null:c.a)}}}var ta=[],ua=[],va=[],wa=[],xa=[],I=!1;function ya(){var a=b.preRun.shift();ta.unshift(a)}var J=0,za=null,K=null;b.preloadedImages={};b.preloadedAudios={};function L(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(b.wasmBinary)return new Uint8Array(b.wasmBinary);if(b.readBinary)return b.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(p){z(p)}}function c(){return b.wasmBinary||!r&&!t||"function"!==typeof fetch?new Promise(function(c){c(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function d(a){function d(a){m=a.exports;if(m.memory){a=m.memory;var c=b.buffer;a.byteLength<c.byteLength&&b.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(a)).set(c);b.buffer=buffer=a;ma()}b.asm=m;b.usingWasm=!0;J--;b.monitorRunDependencies&&b.monitorRunDependencies(J);0==J&&(null!==za&&(clearInterval(za),za=null),K&&(a=K,K=null,a()))}
function e(a){d(a.instance)}function g(a){c().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){b.printErr("failed to asynchronously prepare wasm: "+a);z(a)})}if("object"!==typeof WebAssembly)return b.printErr("no native wasm support detected"),!1;if(!(b.wasmMemory instanceof WebAssembly.Memory))return b.printErr("no native wasm Memory in use"),!1;a.memory=b.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;J++;b.monitorRunDependencies&&b.monitorRunDependencies(J);
if(b.instantiateWasm)try{return b.instantiateWasm(h,d)}catch(ab){return b.printErr("Module.instantiateWasm callback failed with error: "+ab),!1}b.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||L(f)||"function"!==typeof fetch?g(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(e).catch(function(a){b.printErr("wasm streaming compile failed: "+a);b.printErr("falling back to ArrayBuffer instantiation");g(e)});return{}}var e="asm2wasm_matrix_multiply.wast",
f="asm2wasm_matrix_multiply.wasm",g="asm2wasm_matrix_multiply.temp.asm.js";"function"===typeof b.locateFile&&(L(e)||(e=b.locateFile(e)),L(f)||(f=b.locateFile(f)),L(g)||(g=b.locateFile(g)));var h={global:null,env:null,asm2wasm:{"f64-rem":function(a,c){return a%c},"debugger":function(){debugger}},parent:b},m=null;b.asmPreload=b.asm;var k=b.reallocBuffer;b.reallocBuffer=function(a){if("asmjs"===q)var c=k(a);else a:{var d=b.usingWasm?65536:16777216;0<a%d&&(a+=d-a%d);d=b.buffer.byteLength;if(b.usingWasm)try{c=
-1!==b.wasmMemory.grow((a-d)/65536)?b.buffer=b.wasmMemory.buffer:null;break a}catch(kb){c=null;break a}c=void 0}return c};var q="";b.asm=function(a,c){if(!c.table){a=b.wasmTableSize;void 0===a&&(a=1024);var e=b.wasmMaxTableSize;c.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);b.wasmTable=c.table}c.memoryBase||(c.memoryBase=b.STATIC_BASE);
c.tableBase||(c.tableBase=0);(c=d(c))||z("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return c}})();var Aa=[function(){return r}];C=1024;D=C+6192;ua.push();b.STATIC_BASE=C;b.STATIC_BUMP=6192;D+=16;var M=0;function N(){M+=4;return B[M-4>>2]}var Ba={};
function O(a,c){M=c;try{var d=N(),e=N(),f=N();a=0;O.f||(O.f=[null,[],[]],O.l=function(a,c){var d=O.f[a];assert(d);if(0===c||10===c){a=1===a?b.print:b.printErr;a:{for(var e=c=0;d[e];)++e;if(16<e-c&&d.subarray&&fa)c=fa.decode(d.subarray(c,e));else for(e="";;){var f=d[c++];if(!f){c=e;break a}if(f&128){var h=d[c++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var g=d[c++]&63;if(224==(f&240))f=(f&15)<<12|h<<6|g;else{var k=d[c++]&63;if(240==(f&248))f=(f&7)<<18|h<<12|g<<6|k;else{var m=d[c++]&
63;if(248==(f&252))f=(f&3)<<24|h<<18|g<<12|k<<6|m;else{var q=d[c++]&63;f=(f&1)<<30|h<<24|g<<18|k<<12|m<<6|q}}}65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}}a(c);d.length=0}else d.push(c)});for(c=0;c<f;c++){for(var g=B[e+8*c>>2],h=B[e+(8*c+4)>>2],m=0;m<h;m++)O.l(d,A[g+m]);a+=h}return a}catch(k){return"undefined"!==typeof FS&&k instanceof FS.c||z(k),-k.g}}
function P(a,c){Ca=a;Da=c;if(!Q)return 1;if(0==a)R=function(){var a=Math.max(0,Ea+c-S())|0;setTimeout(T,a)},U="timeout";else if(1==a)R=function(){Fa(T)},U="rAF";else if(2==a){if("undefined"===typeof setImmediate){var d=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),d.shift()()},!0);setImmediate=function(a){d.push(a);t?(void 0===b.setImmediates&&(b.setImmediates=[]),b.setImmediates.push(a),postMessage({target:"setimmediate"})):
postMessage("setimmediate","*")}}R=function(){setImmediate(T)};U="immediate"}return 0}function S(){z()}
function Ga(a,c,d,e,f){b.noExitRuntime=!0;assert(!Q,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Q=a;Ha=e;var g="undefined"!==typeof e?function(){b.dynCall_vi(a,e)}:function(){b.dynCall_v(a)};var h=V;T=function(){if(!y)if(0<Ia.length){var a=Date.now(),c=Ia.shift();c.m(c.a);if(Ja){var d=Ja,e=0==d%1?d-1:Math.floor(d);Ja=c.A?e:(8*d+(e+.5))/9}console.log('main loop blocker "'+
c.name+'" took '+(Date.now()-a)+" ms");b.setStatus&&(a=b.statusMessage||"Please wait...",c=Ja,d=Ka.B,c?c<d?b.setStatus(a+" ("+(d-c)+"/"+d+")"):b.setStatus(a):b.setStatus(""));h<V||setTimeout(T,0)}else if(!(h<V))if(La=La+1|0,1==Ca&&1<Da&&0!=La%Da)R();else{0==Ca&&(Ea=S());"timeout"===U&&b.b&&(b.printErr("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
U="");a:if(!(y||b.preMainLoop&&!1===b.preMainLoop())){try{g()}catch(v){if(v instanceof w)break a;v&&"object"===typeof v&&v.stack&&b.printErr("exception thrown: "+[v,v.stack]);throw v;}b.postMainLoop&&b.postMainLoop()}h<V||("object"===typeof SDL&&SDL.audio&&SDL.audio.v&&SDL.audio.v(),R())}};f||(c&&0<c?P(0,1E3/c):P(1,1),R());if(d)throw"SimulateInfiniteLoop";}var R=null,U="",V=0,Q=null,Ha=0,Ca=0,Da=0,La=0,Ia=[],Ka={},Ea,T,Ja,Ma=!1,Na=!1,Oa=[];
function Pa(){function a(){Na=document.pointerLockElement===b.canvas||document.mozPointerLockElement===b.canvas||document.webkitPointerLockElement===b.canvas||document.msPointerLockElement===b.canvas}b.preloadPlugins||(b.preloadPlugins=[]);if(!Qa){Qa=!0;try{W=!0}catch(d){W=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Ra="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:W?null:console.log("warning: no BlobBuilder");
X="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;b.h||"undefined"!==typeof X||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),b.h=!0);b.preloadPlugins.push({canHandle:function(a){return!b.h&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,c,f,g){var d=null;if(W)try{d=new Blob([a],{type:Sa(c)}),d.size!==a.length&&(d=new Blob([(new Uint8Array(a)).buffer],{type:Sa(c)}))}catch(q){ea("Blob constructor present but fails: "+
q+"; falling back to blob builder")}d||(d=new Ra,d.append((new Uint8Array(a)).buffer),d=d.getBlob());var e=X.createObjectURL(d),k=new Image;k.onload=function(){assert(k.complete,"Image "+c+" could not be decoded");var d=document.createElement("canvas");d.width=k.width;d.height=k.height;d.getContext("2d").drawImage(k,0,0);b.preloadedImages[c]=d;X.revokeObjectURL(e);f&&f(a)};k.onerror=function(){console.log("Image "+e+" could not be decoded");g&&g()};k.src=e}});b.preloadPlugins.push({canHandle:function(a){return!b.F&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,c,f,g){function d(d){k||(k=!0,b.preloadedAudios[c]=d,f&&f(a))}function e(){k||(k=!0,b.preloadedAudios[c]=new Audio,g&&g())}var k=!1;if(W){try{var q=new Blob([a],{type:Sa(c)})}catch(v){return e()}q=X.createObjectURL(q);var p=new Audio;p.addEventListener("canplaythrough",function(){d(p)},!1);p.onerror=function(){if(!k){console.log("warning: browser could not fully decode audio "+c+", trying slower base64 approach");for(var e="",f=0,g=0,h=
0;h<a.length;h++)for(f=f<<8|a[h],g+=8;6<=g;){var m=f>>g-6&63;g-=6;e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[m]}2==g?(e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],e+="=="):4==g&&(e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],e+="=");p.src="data:audio/x-"+c.substr(-3)+";base64,"+e;d(p)}};p.src=q;Ta(function(){d(p)})}else return e()}});var c=b.canvas;c&&(c.requestPointerLock=c.requestPointerLock||c.mozRequestPointerLock||
c.webkitRequestPointerLock||c.msRequestPointerLock||function(){},c.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},c.exitPointerLock=c.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),b.elementPointerLock&&
c.addEventListener("click",function(a){!Na&&b.canvas.requestPointerLock&&(b.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function Ua(a,c,d,e){if(c&&b.b&&a==b.canvas)return b.b;if(c){var f={antialias:!1,alpha:!1};if(e)for(var g in e)f[g]=e[g];if(f=GL.createContext(a,f))var h=GL.getContext(f).GLctx}else h=a.getContext("2d");if(!h)return null;d&&(c||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),b.b=h,c&&GL.D(f),b.G=c,Oa.forEach(function(a){a()}),Pa());return h}var Va=!1,Wa=void 0,Y=void 0;
function Xa(a,c,d){function e(){Ma=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),Wa&&f.requestPointerLock(),Ma=!0,Y&&("undefined"!=typeof SDL&&
(B[SDL.screen>>2]=la[SDL.screen>>2]|8388608),Ya())):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),Y&&("undefined"!=typeof SDL&&(B[SDL.screen>>2]=la[SDL.screen>>2]&-8388609),Ya()));if(b.onFullScreen)b.onFullScreen(Ma);if(b.onFullscreen)b.onFullscreen(Ma);Za(f)}Wa=a;Y=c;$a=d;"undefined"===typeof Wa&&(Wa=!0);"undefined"===typeof Y&&(Y=!1);"undefined"===typeof $a&&($a=null);var f=b.canvas;Va||(Va=!0,document.addEventListener("fullscreenchange",e,!1),document.addEventListener("mozfullscreenchange",
e,!1),document.addEventListener("webkitfullscreenchange",e,!1),document.addEventListener("MSFullscreenChange",e,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);d?g.requestFullscreen({H:d}):
g.requestFullscreen()}function bb(a,c,d){b.printErr("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");bb=function(a,c,d){return Xa(a,c,d)};return Xa(a,c,d)}var Z=0;function cb(a){var c=Date.now();if(0===Z)Z=c+1E3/60;else for(;c+2>=Z;)Z+=1E3/60;setTimeout(a,Math.max(Z-c,0))}
function Fa(a){"undefined"===typeof window?cb(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||cb),window.requestAnimationFrame(a))}function Ta(a){b.noExitRuntime=!0;setTimeout(function(){y||a()},1E4)}
function Sa(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var db=[];function Ya(){var a=b.canvas;db.forEach(function(c){c(a.width,a.height)})}
function Za(a,c,d){c&&d?(a.w=c,a.u=d):(c=a.w,d=a.u);var e=c,f=d;b.forcedAspectRatio&&0<b.forcedAspectRatio&&(e/f<b.forcedAspectRatio?e=Math.round(f*b.forcedAspectRatio):f=Math.round(e/b.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*g)}Y?
(a.width!=e&&(a.width=e),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=c&&(a.width=c),a.height!=d&&(a.height=d),"undefined"!=typeof a.style&&(e!=c||f!=d?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Qa,W,Ra,X,$a;
b.requestFullScreen=function(a,c,d){b.printErr("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");b.requestFullScreen=b.requestFullscreen;bb(a,c,d)};b.requestFullscreen=function(a,c,d){Xa(a,c,d)};b.requestAnimationFrame=function(a){Fa(a)};b.setCanvasSize=function(a,c,d){Za(b.canvas,a,c);d||Ya()};b.pauseMainLoop=function(){R=null;V++};b.resumeMainLoop=function(){V++;var a=Ca,c=Da,d=Q;Q=null;Ga(d,0,!1,Ha,!0);P(a,c);R()};
b.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};b.createContext=function(a,c,d,e){return Ua(a,c,d,e)};
u?S=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?S=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?S=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?S=function(){return performance.now()}:S=Date.now;assert(!na);var eb=D;D=D+4+15&-16;F=eb;oa=E=da(D);pa=oa+sa;qa=da(pa);B[F>>2]=qa;na=!0;b.wasmTableSize=8;b.wasmMaxTableSize=8;b.i={};
b.j={abort:z,enlargeMemory:function(){ra()},getTotalMemory:function(){return G},abortOnCannotGrowMemory:ra,___setErrNo:function(a){b.___errno_location&&(B[b.___errno_location()>>2]=a);return a},___syscall140:function(a,c){M=c;try{var d=Ba.o();N();var e=N(),f=N(),g=N();FS.C(d,e,g);B[f>>2]=d.position;d.s&&0===e&&0===g&&(d.s=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.c||z(h),-h.g}},___syscall146:O,___syscall54:function(a,c){M=c;return 0},___syscall6:function(a,c){M=c;try{var d=
Ba.o();FS.close(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.c||z(e),-e.g}},_emscripten_asm_const_i:function(a){return Aa[a]()},_emscripten_cancel_main_loop:function(){R=null;V++;Q=null},_emscripten_get_now:S,_emscripten_memcpy_big:function(a,c,d){A.set(A.subarray(c,c+d),a);return a},_emscripten_set_main_loop:Ga,_emscripten_set_main_loop_timing:P,_exit:function(a){b.exit(a)},DYNAMICTOP_PTR:F,STACKTOP:E};var fb=b.asm(b.i,b.j,buffer);b.asm=fb;
b._main=function(){return b.asm._main.apply(null,arguments)};var ia=b.stackAlloc=function(){return b.asm.stackAlloc.apply(null,arguments)};b.dynCall_v=function(){return b.asm.dynCall_v.apply(null,arguments)};b.asm=fb;function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}w.prototype=Error();w.prototype.constructor=w;K=function gb(){b.calledRun||hb([].concat(b.arguments));b.calledRun||(K=gb)};
b.callMain=function(a){a=a||[];I||(I=!0,H(ua));var c=a.length+1,d=ia(4*(c+1));B[d>>2]=ha(b.thisProgram);for(var e=1;e<c;e++)B[(d>>2)+e]=ha(a[e-1]);B[(d>>2)+c]=0;try{var f=b._main(c,d,0);ib(f,!0)}catch(g){g instanceof w||("SimulateInfiniteLoop"==g?b.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),b.printErr("exception thrown: "+a),b.quit(1,g)))}finally{}};
function hb(a){function c(){if(!b.calledRun&&(b.calledRun=!0,!y)){I||(I=!0,H(ua));H(va);if(b.onRuntimeInitialized)b.onRuntimeInitialized();b._main&&jb&&b.callMain(a);if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();xa.unshift(c)}H(xa)}}a=a||b.arguments;if(!(0<J)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)ya();H(ta);0<J||b.calledRun||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},
1);c()},1)):c())}}b.run=hb;function ib(a,c){if(!c||!b.noExitRuntime||0!==a){if(!b.noExitRuntime&&(y=!0,E=void 0,H(wa),b.onExit))b.onExit(a);u&&process.exit(a);b.quit(a,new w(a))}}b.exit=ib;function z(a){if(b.onAbort)b.onAbort(a);void 0!==a?(b.print(a),b.printErr(a),a=JSON.stringify(a)):a="";y=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}b.abort=z;if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();var jb=!0;
b.noInitialRun&&(jb=!1);b.noExitRuntime=!0;hb([].concat(b.arguments));
