var a;a||(a=typeof Module !== 'undefined' ? Module : {});var k={},m;for(m in a)a.hasOwnProperty(m)&&(k[m]=a[m]);a.arguments=[];a.thisProgram="./this.program";a.quit=function(b,c){throw c;};a.preRun=[];a.postRun=[];var n=!1,q=!1,r=!1,t=!1;
if(a.ENVIRONMENT)if("WEB"===a.ENVIRONMENT)n=!0;else if("WORKER"===a.ENVIRONMENT)q=!0;else if("NODE"===a.ENVIRONMENT)r=!0;else if("SHELL"===a.ENVIRONMENT)t=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else n="object"===typeof window,q="function"===typeof importScripts,r="object"===typeof process&&"function"===typeof require&&!n&&!q,t=!n&&!r&&!q;
if(r){var u,v;a.read=function(b,c){u||(u=require("fs"));v||(v=require("path"));b=v.normalize(b);b=u.readFileSync(b);return c?b:b.toString()};a.readBinary=function(b){b=a.read(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);return b};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(b){if(!(b instanceof w))throw b;});process.on("unhandledRejection",
function(){process.exit(1)});a.inspect=function(){return"[Emscripten Module object]"}}else if(t)"undefined"!=typeof read&&(a.read=function(b){return read(b)}),a.readBinary=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");assert("object"===typeof b);return b},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=arguments),"function"===typeof quit&&(a.quit=function(b){quit(b)});else if(n||q)a.read=function(b){var c=
new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},q&&(a.readBinary=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),a.readAsync=function(b,c,e){var d=new XMLHttpRequest;d.open("GET",b,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?c(d.response):e()};d.onerror=e;d.send(null)},a.setWindowTitle=function(b){document.title=b};
a.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;a.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||a.print;a.print=a.print;a.printErr=a.printErr;for(m in k)k.hasOwnProperty(m)&&(a[m]=k[m]);k=void 0;function aa(b){var c;c||(c=16);return Math.ceil(b/c)*c}var x=0;function assert(b,c){b||y("Assertion failed: "+c)}var ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function ca(b){for(var c=0,e=0;e<b.length;++e){var d=b.charCodeAt(e);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|b.charCodeAt(++e)&1023);127>=d?++c:c=2047>=d?c+2:65535>=d?c+3:2097151>=d?c+4:67108863>=d?c+5:c+6}var g=c+1;c=da(g);e=c;d=ea;if(0<g){g=e+g-1;for(var h=0;h<b.length;++h){var f=b.charCodeAt(h);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|b.charCodeAt(++h)&1023);if(127>=f){if(e>=g)break;d[e++]=f}else{if(2047>=f){if(e+1>=g)break;d[e++]=192|f>>6}else{if(65535>=f){if(e+2>=g)break;d[e++]=224|f>>
12}else{if(2097151>=f){if(e+3>=g)break;d[e++]=240|f>>18}else{if(67108863>=f){if(e+4>=g)break;d[e++]=248|f>>24}else{if(e+5>=g)break;d[e++]=252|f>>30;d[e++]=128|f>>24&63}d[e++]=128|f>>18&63}d[e++]=128|f>>12&63}d[e++]=128|f>>6&63}d[e++]=128|f&63}}d[e]=0}return c}var buffer,ea,z,fa,A;
function ha(){a.HEAP8=ea=new Int8Array(buffer);a.HEAP16=fa=new Int16Array(buffer);a.HEAP32=A=new Int32Array(buffer);a.HEAPU8=z=new Uint8Array(buffer);a.HEAPU16=new Uint16Array(buffer);a.HEAPU32=new Uint32Array(buffer);a.HEAPF32=new Float32Array(buffer);a.HEAPF64=new Float64Array(buffer)}var B,C,D,E,F,G,H,I;B=C=E=F=G=H=I=0;D=!1;
function ia(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+J+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var K=a.TOTAL_STACK||5242880,J=a.TOTAL_MEMORY||268435456;J<K&&a.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+J+"! (TOTAL_STACK="+K+")");
a.buffer?buffer=a.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(a.wasmMemory=new WebAssembly.Memory({initial:J/65536,maximum:J/65536}),buffer=a.wasmMemory.buffer):buffer=new ArrayBuffer(J),a.buffer=buffer);ha();A[0]=1668509029;fa[1]=25459;if(115!==z[2]||99!==z[3])throw"Runtime error: expected the system to be little-endian!";
function L(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c();else{var e=c.m;"number"===typeof e?void 0===c.b?a.dynCall_v(e):a.dynCall_vi(e,c.b):e(void 0===c.b?null:c.b)}}}var ja=[],M=[],ka=[],la=[],ma=[],N=!1;function na(){var b=a.preRun.shift();ja.unshift(b)}var P=0,Q=null,R=null;a.preloadedImages={};a.preloadedAudios={};function S(b){return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}
(function(){function b(){try{if(a.wasmBinary)return new Uint8Array(a.wasmBinary);if(a.readBinary)return a.readBinary(g);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(O){y(O)}}function c(){return a.wasmBinary||!n&&!q||"function"!==typeof fetch?new Promise(function(c){c(b())}):fetch(g,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+g+
"'";return b.arrayBuffer()}).catch(function(){return b()})}function e(b){function e(b){l=b.exports;if(l.memory){b=l.memory;var c=a.buffer;b.byteLength<c.byteLength&&a.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(b)).set(c);a.buffer=buffer=b;ha()}a.asm=l;a.usingWasm=!0;F=E+K;G=E;a.asm.stackRestore(F);P--;a.monitorRunDependencies&&a.monitorRunDependencies(P);0==P&&(null!==Q&&(clearInterval(Q),
Q=null),R&&(b=R,R=null,b()))}function d(b){e(b.instance)}function O(b){c().then(function(b){return WebAssembly.instantiate(b,f)}).then(b).catch(function(b){a.printErr("failed to asynchronously prepare wasm: "+b);y(b)})}if("object"!==typeof WebAssembly)return a.printErr("no native wasm support detected"),!1;if(!(a.wasmMemory instanceof WebAssembly.Memory))return a.printErr("no native wasm Memory in use"),!1;b.memory=a.wasmMemory;f.global={NaN:NaN,Infinity:Infinity};f["global.Math"]=Math;f.env=b;P++;
a.monitorRunDependencies&&a.monitorRunDependencies(P);if(a.instantiateWasm)try{return a.instantiateWasm(f,e)}catch(va){return a.printErr("Module.instantiateWasm callback failed with error: "+va),!1}a.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||S(g)||"function"!==typeof fetch?O(d):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),f).then(d).catch(function(b){a.printErr("wasm streaming compile failed: "+b);a.printErr("falling back to ArrayBuffer instantiation");
O(d)});return{}}var d="wasmbackend_havlak.wast",g="wasmbackend_havlak.wasm",h="wasmbackend_havlak.temp.asm.js";"function"===typeof a.locateFile&&(S(d)||(d=a.locateFile(d)),S(g)||(g=a.locateFile(g)),S(h)||(h=a.locateFile(h)));var f={global:null,env:null,asm2wasm:{"f64-rem":function(b,c){return b%c},"debugger":function(){debugger}},parent:a},l=null;a.asmPreload=a.asm;var p=a.reallocBuffer;a.reallocBuffer=function(b){if("asmjs"===Z)var c=p(b);else a:{var e=a.usingWasm?65536:16777216;0<b%e&&(b+=e-b%e);
e=a.buffer.byteLength;if(a.usingWasm)try{c=-1!==a.wasmMemory.grow((b-e)/65536)?a.buffer=a.wasmMemory.buffer:null;break a}catch(za){c=null;break a}c=void 0}return c};var Z="";a.asm=function(b,c){b={};for(var d in c){var f=d;"_"==f[0]&&(f=f.substr(1));b[f]=c[d]}c=b;c.table||(d=a.wasmTableSize,void 0===d&&(d=1024),b=a.wasmMaxTableSize,c.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==b?new WebAssembly.Table({initial:d,maximum:b,element:"anyfunc"}):new WebAssembly.Table({initial:d,
element:"anyfunc"}):Array(d),a.wasmTable=c.table);c.memoryBase||(c.memoryBase=a.STATIC_BASE);c.tableBase||(c.tableBase=0);(d=e(c))||y("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return d}})();B=1024;C=B+6512;M.push();a.STATIC_BASE=B;a.STATIC_BUMP=6512;C+=16;function T(){return!!T.a}var U=0;function V(){U+=4;return A[U-4>>2]}var oa={};
function W(b,c){U=c;try{var e=V(),d=V(),g=V();b=0;W.a||(W.a=[null,[],[]],W.i=function(b,c){var d=W.a[b];assert(d);if(0===c||10===c){b=1===b?a.print:a.printErr;a:{for(var e=c=0;d[e];)++e;if(16<e-c&&d.subarray&&ba)c=ba.decode(d.subarray(c,e));else for(e="";;){var f=d[c++];if(!f){c=e;break a}if(f&128){var g=d[c++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var h=d[c++]&63;if(224==(f&240))f=(f&15)<<12|g<<6|h;else{var l=d[c++]&63;if(240==(f&248))f=(f&7)<<18|g<<12|h<<6|l;else{var p=d[c++]&
63;if(248==(f&252))f=(f&3)<<24|g<<18|h<<12|l<<6|p;else{var Z=d[c++]&63;f=(f&1)<<30|g<<24|h<<18|l<<12|p<<6|Z}}}65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}}b(c);d.length=0}else d.push(c)});for(c=0;c<g;c++){for(var h=A[d+8*c>>2],f=A[d+(8*c+4)>>2],l=0;l<f;l++)W.i(e,z[h+l]);b+=f}return b}catch(p){return"undefined"!==typeof FS&&p instanceof FS.c||y(p),-p.f}}var X={},pa=1;
function Y(b,c){Y.a||(Y.a={});b in Y.a||(a.dynCall_v(c),Y.a[b]=1)}function qa(){a.___errno_location&&(A[a.___errno_location()>>2]=12)}assert(!D);var ra=C;C=C+4+15&-16;I=ra;E=F=aa(C);G=E+K;H=aa(G);A[I>>2]=H;D=!0;a.g={};
a.h={abort:y,_pthread_getspecific:function(b){return X[b]||0},_pthread_setspecific:function(b,c){if(!(b in X))return 22;X[b]=c;return 0},___cxa_throw:function(b){"uncaught_exception"in T?T.a++:T.a=1;throw b+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},___syscall54:function(b,c){U=c;return 0},_pthread_once:Y,___syscall6:function(b,c){U=c;try{var e=oa.j();FS.close(e);return 0}catch(d){return"undefined"!==
typeof FS&&d instanceof FS.c||y(d),-d.f}},_sbrk:function(b){b|=0;var c=A[I>>2]|0;var e=c+b|0;if(0<(b|0)&(e|0)<(c|0)|0>(e|0))return ia()|0,qa(),-1;A[I>>2]=e;if(b=(e|0)>(J|0))ia(),b=!0;return b?(A[I>>2]=c,qa(),-1):c|0},___cxa_allocate_exception:function(b){return sa(b)},_pthread_key_create:function(b){if(0==b)return 22;A[b>>2]=pa;X[pa]=0;pa++;return 0},___syscall140:function(b,c){U=c;try{var e=oa.j();V();var d=V(),g=V(),h=V();FS.o(e,d,h);A[g>>2]=e.position;e.l&&0===d&&0===h&&(e.l=null);return 0}catch(f){return"undefined"!==
typeof FS&&f instanceof FS.c||y(f),-f.f}},___syscall146:W};var ta=a.asm(a.g,a.h,buffer);a.asm=ta;var sa=a._malloc=function(){return a.asm.malloc.apply(null,arguments)};a._stackAlloc=function(){return a.asm.stackAlloc.apply(null,arguments)};a._main=function(){return a.asm.main.apply(null,arguments)};a.dynCall_vi=function(){return a.asm.dynCall_vi.apply(null,arguments)};a._stackRestore=function(){return a.asm.stackRestore.apply(null,arguments)};
a.dynCall_ii=function(){return a.asm.dynCall_ii.apply(null,arguments)};a.dynCall_v=function(){return a.asm.dynCall_v.apply(null,arguments)};var da=a._stackAlloc;a.asm=ta;function w(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}w.prototype=Error();w.prototype.constructor=w;R=function ua(){a.calledRun||wa([].concat(a.arguments));a.calledRun||(R=ua)};
a.callMain=function(b){b=b||[];N||(N=!0,L(M));var c=b.length+1,e=da(4*(c+1));A[e>>2]=ca(a.thisProgram);for(var d=1;d<c;d++)A[(e>>2)+d]=ca(b[d-1]);A[(e>>2)+c]=0;try{var g=a._main(c,e,0);xa(g,!0)}catch(h){h instanceof w||("SimulateInfiniteLoop"==h?a.noExitRuntime=!0:((b=h)&&"object"===typeof h&&h.stack&&(b=[h,h.stack]),a.printErr("exception thrown: "+b),a.quit(1,h)))}finally{}};
function wa(b){function c(){if(!a.calledRun&&(a.calledRun=!0,!x)){N||(N=!0,L(M));L(ka);if(a.onRuntimeInitialized)a.onRuntimeInitialized();a._main&&ya&&a.callMain(b);if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();ma.unshift(c)}L(ma)}}b=b||a.arguments;if(!(0<P)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)na();L(ja);0<P||a.calledRun||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},
1);c()},1)):c())}}a.run=wa;function xa(b,c){if(!c||!a.noExitRuntime||0!==b){if(!a.noExitRuntime&&(x=!0,F=void 0,L(la),a.onExit))a.onExit(b);r&&process.exit(b);a.quit(b,new w(b))}}a.exit=xa;function y(b){if(a.onAbort)a.onAbort(b);void 0!==b?(a.print(b),a.printErr(b),b=JSON.stringify(b)):b="";x=!0;throw"abort("+b+"). Build with -s ASSERTIONS=1 for more info.";}a.abort=y;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();var ya=!0;
a.noInitialRun&&(ya=!1);a.noExitRuntime=!0;wa([].concat(a.arguments));
